name: DockerBuildStagePipeline

on:
  push:
    branches: [develop]

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: docker build
        run: docker image build -t sametdemirel/atolye15demo:latest .
      - name: docker image
        run: docker images
      - name: docker login
        run: docker login -u ${{ secrets.USER }} -p ${{ secrets.PASSWORD }}
      - name: docker push
        run: docker push sametdemirel/atolye15demo:latest
  k8s-stage:
    runs-on: ubuntu-latest
    needs: docker-image-build
    name: k8s-stage
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: kube create
        run: mkdir /home/runner/.kube
      - name: echo kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config
      - name: kubectl control
        run: kubectl get nodes
      - name: change namespace
        run: kubectl config set-context --current --namespace=stage
      - name: kubectl apply deploy
        run: kubectl apply -f kubernetes/Stage/deployment.yaml
      - name: service enable wait
        run: sleep 45
      - name: service list
        run: kubectl get service
  stage-email:
    runs-on: ubuntu-latest
    needs: k8s-stage
    name: Send mail stage
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          server_address: smtp-relay.sendinblue.com
          server_port: 587
          username: akinturk.0.01@gmail.com
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Stage deploy
          to: demirel.141@hotmail.com
          from: akinturk.0.01@gmail.com
          html_body: "<html><head></head><body><p>Deployed,</p>Satage deployed.</p></body></html>"
